### ISSUE TITLE
Add Vertical Position Paint 1 [YPN1] axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#116]
## Font Project introducing the axis

Bitcount (still a private project)

## Short description of what the axis does

The position of the background color moves up and down. Negative values go down and positive values go up in the Y dimension.

## Image

![COLY](https://user-images.githubusercontent.com/48698976/226986439-9a06135c-b88b-43a4-9aaf-eec8bc1e23df.gif)

## Why is the axis needed

The font experiments with generating a "background drawing" that is shifted and scaled using the shape pixels as masks. There is currently working on a version where that background contains a number of color shapes. With an 'x' and 'y' position axes the layers of color shapes can be moved/selected behind the glyph pixel masks.

## Axis metadata fields

```
# COLY, based on a still private project
tag: "COLY"
display_name: "Color Position in Y"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the background color moves up and down."
  " Negative values go down and positive values go up,"
  " in the Y dimension."
````

**Comment by kenmcd** [comment]
> Color position in Y

Should "position" be capitalized?
e.g. Color Position in Y

**Comment by vv-monsalve** [comment]
```
# YLY1 based on a still private project
tag: "YLY1"
display_name: "Y position Layer 1"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the layer moves left and right. "
  " Negative values to the left and positive values to the right, "
  " in the Y dimension."
````

An additional Axis `YLY2` should be registered for the second layer, so its axis metadata fields would be

```
# YLY2 based on a still private project
tag: "YLY2"
display_name: "Y position Layer 2"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the layer moves left and right. Negative values"
  " to the left and positive values to the right, in the Y dimension."
  " This Layer is closer to the user than Layer 1."
````

**Comment by davelab6** [comment]
This is agreed with me, @chrissimpkins and @evanwadams :)

**Comment by vv-monsalve** [comment]
In relation to the [comment made in "LYSZ"](https://github.com/googlefonts/axisregistry/issues/117#issuecomment-1652606877), should this axis better be `Vertical Position Paint 1` tag `YPN1`

**Comment by vv-monsalve** [comment]
Last axis definitions revised

#### **`YPN1`**

```
# YPN1 based on a still private project
tag: "YPN1"
display_name: "Vertical Position Paint 1"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the paint moves up and down. Negative values"
  " move down and positive values up. Paint 1 is behind Paint 2."
````

#### **`YPN2`**

```
# YPN2 based on a still private project
tag: "YPN2"
display_name: "Vertical Position Paint 2"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the paint moves up and down. Negative values"
  " move down and positive values up. Paint 2 is in front of Paint 1."
````
