### ISSUE TITLE
Add Element Expansion [ELXP] axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#128]
### Font project(s) using the axis

Bitcount (still a private project)

### Short description of what the axis does

As the Open axis increases, splits the mask pixels into four quarters while expanding them out into an open space.

### Image

![Open-axis](https://user-images.githubusercontent.com/48698976/226979205-55636676-297b-4680-96dc-0f3773cf3fb1.gif)

### Why is the axis needed

The only other similar axis recorded is `Element Grid ELGR`. However, the proposed `OPEN` axis not only changes the number of elements, but also moves them away from a central position, providing a sense of expansion that could be used for animation purposes.

### Axis metadata fields

```
#ELOP based on a still private project
tag: "ELOP"
display_name: "Element Opening"
min_value: 0
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  “As the Open axis increases, splits the mask pixels into”
  “ four quarters while expanding them out into an open space.
````

**Comment by vv-monsalve** [comment]
`Element Expansion ELXP` is proposed to convey the axis effect in the font more explicitly.

**Comment by vv-monsalve** [comment]
```
#ELXP based on a still private project
tag: "ELXP"
display_name: "Element Expansion"
min_value: 0
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  “As the Element Expansion increases, it splits the pixels into”
  “ four quarters while expanding them apart.”
````

**Comment by yanone** [comment]
@vv-monsalve asked me to review all the axes proposals aimed at Bitcount, and this goes for all of them:

The only thing I'm confused about are the units proposed. In this issue they’re not defined, but in the other issues they are, as percentages, from -100% to +100%, so I'm guessing the same applies here.

Percentage of what? Each element’s own size? And then, when it comes to shrinking and expanding, what does -100% and +100% mean? 

-100% is clearly defined as an element's size going to zero, so disappearing.
But +100%? I interpret it as a maximum of 2x its previous size. Is that enough? 

I find that the axes are very specific to Bitcount and won't be applicable to other fonts. If that's the idea, then I have no issues with the proposals.

But if axes are meant to be generally applicable, then I would gauge a font unit-based approach to size and position and expansion.

**Comment by vv-monsalve** [comment]
`ELXP` was created as a [relative axis](https://googlefonts.github.io/gf-guide/axis-registry.html#relative-range-axes) with a percentage so that each font project could interpret the element expansion according to their needs. This was done to ensure that it was not specific to any particular project and could be interpreted in various ways. It would also depend on the element size case of each case, so it could 2x, 3x or any other interpretation independent of a type measurement.

Currently, the range does not include a negative portion. However, it can be added if a font project requires it in the future, such as for disappearing or shrinking purposes.

**Comment by vv-monsalve** [comment]
The description should be improved without restricting it to four quarters @davelab6

**Comment by chrissimpkins** [comment]
Element Expansion approved with the axis range and default values defined in https://github.com/googlefonts/axisregistry/issues/128#issuecomment-1489376738.  Ready to onboard when we update the description.

**Comment by vv-monsalve** [comment]
Axis definitions agreed:

```
#ELXP based on a still private project
tag: "ELXP"
display_name: "Element Expansion"
min_value: 0
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  “As the Element Expansion axis progresses, the elements move apart.”
````
