### ISSUE TITLE
Add Rotation in Z [ZROT] axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#129]
### Requirements

- [x] I have inspected the current [Axis Registry](https://github.com/googlefonts/axisregistry/tree/main/Lib/axisregistry/data) and there is not a registered custom axis that could be used for the variation purpose on the upcoming font project.
- [x] The metadata fields of the proposed axis meet the *Axis Requirements* as specified in the Protocol (linked above).

### Font project(s) using the axis

Brand font - private project

### Short description of what the axis does

Glyphs rotate back and forwards, negative values go back and positive values go forward, in the Z dimension.

### Image

![ZROT](https://user-images.githubusercontent.com/48698976/228649923-eefb7bc3-059f-47a1-addc-88b40f785a0e.gif)

### Why is the axis needed

The other Rotation axes refer to other rotation orientation.

### Axis metadata fields

```
#(ZROT) based on (brand font private project)
tag: "ZROT"
display_name: "Rotation in Z"
min_value: 0
default_value: 0
max_value: 100
precision: 
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Glyphs rotate up and down, negative values tilt down"
  " and positive values tilt up, in the Y dimension."
````

**Comment by vv-monsalve** [comment]
After the last revision axis was agreed upon to be registered consistently with the other `ROT` axis.

```
#(ZROT) based on (brand font private project)
tag: "ZROT"
display_name: "Rotation in Z"
min_value: -180
default_value: 0
max_value: 180
precision: 
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Glyphs rotate left and right, negative values to the left"
  " and positive values to the right, in the Z dimension."
````
