### ISSUE TITLE
Add Round (ROND) axis

### ISSUE THREAD

**Issue by davelab6** [googlefonts/axisregistry#59]
This is needed for an internal project that @chrissimpkins is leading, and is distinct from SOFT because that gives a "dipped in chocolate" treatment to each overall letterform, whereas the internal typeface only rounds terminals, using the quadratic bezier interpolated offcurve point technique.

**Comment by chrissimpkins** [comment]
David Berlow recommends the following:

- **name**: "Terminal Rounding"
- **description**: "Instances represent variations from square terminals to round terminals of the diameter of the local stem in percent of change"
- **value interpretation**: "Values can be interpreted as the circumference of a circle where 100% is the nominal stem weight"
- **range values**: 0 to 100
- **default value**: "Default can be anything from 0-100, depending on stem shape of default."

**Comment by davelab6** [comment]
Another internal project, for iconography, needs both round and sharp, so the negative range of this axis can go sharp

**Comment by vv-monsalve** [comment]
> Another internal project, for iconography, needs both round and sharp, so the negative range of this axis can go sharp

I think this is the whole idea around [Terminal Shape](https://github.com/googlefonts/axisregistry/issues/43) axis, and the same reason why I've been advocating to register it to control terminal shapes from Pointy (we've discussed about avoiding sharp) to Rounded.

**Comment by vv-monsalve** [comment]
On an internal chat conversation

Dave said:
> except for round which has a negative end for sharpness

> yeah i am in a sense advocating duplication of sharp as its own axis, and as a negative end of round


The values of this axis should be:

````
min_value: -100
default_value: 0
max_value: 100
precision: 0
````

**Comment by vv-monsalve** [comment]
After today's meeting review of the expected behavior, this axis doesn't need the negative part portion of the range.

So following up on that discussion plus the ones we've had around new axis registers, the suggestions for the axis would be:

```
tag: "ROND"
display_name: "Roundness"
min_value: 0
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "Adjust variations from square shapes to increasingly rounded forms."

```
